name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ github.ref }}
      - run: pip install mkdocs mkdocs-material
      - run: python3 -m mkdocs gh-deploy --force